name: Run Campaign Simulations

# This GitHub Actions workflow executes the campaign simulation script on a
# recurring basis.  It uses Python 3.11 to run the provided `simulate.py`
# script and writes the results to a CSV file.  The results can be used
# to monitor projected performance of different budget and duration
# scenarios.  Adjust the cron schedule as needed; the current setting
# triggers the workflow every day at 16:00 UTC (9 am Pacific Time).

on:
  # Manual trigger via the GitHub UI
  workflow_dispatch:
  # Scheduled trigger: every day at 16:00 UTC
  schedule:
    - cron: '0 16 * * *'

jobs:
  simulations:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository contents
      - uses: actions/checkout@v3

      # Set up a Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      # Install any Python dependencies required by the simulation script
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install optional packages for future extensions (e.g., pandas for CSV handling)
          python -m pip install matplotlib pandas

      # Run the campaign simulation script and write results to a CSV file
      - name: Run simulations
        run: |
          python simulate.py --output simulation_results.csv

      # Optionally, display the CSV contents in the workflow logs for debugging
      - name: Show simulation results
        run: |
          python -c "import pandas as pd; print(pd.read_csv('simulation_results.csv'))"